/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/
package com.github.vsams14.euler;

import java.util.ArrayList;

public class solver045 {
	ArrayList<Long> pent = new ArrayList<Long>();
	ArrayList<Long> hex = new ArrayList<Long>();
	
	public solver045(){
		find();
	}
	
	private void find(){
		for(long i=1;i<=100000; i++){
			pent.add(pent(i));
			hex.add(hex(i));
			long tri = tri(i);
			if(pent.contains(tri)&&hex.contains(tri))utils.println(tri+"");
		}
	}
	
	private long tri(long n){
		return (n*(n+1))/2;
	}
	
	private long pent(long n){
		return (n*(3*n-1))/2;
	}
	
	private long hex(long n){
		return n*(2*n-1);
	}
}
