/*
Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten 
pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 
70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and 
difference are pentagonal and D = |Pk - Pj| is minimised; what is the value of 
D?
*/

package com.github.vsams14.euler;

public class solver44 {
	public solver44(){
		find();
	}
	
	private void find(){
		boolean solved = false;
		int i=2160;
		while(i<2164 || !solved){
			long n = utils.pent(i);
			for(long j=n-1; j>0; j--){
				if(!utils.isPent(j)) continue;
				long sum = n+j;
				long dif = n-j;
				//utils.println(n+":"+j+":"+sum+":"+dif);
				if(utils.isPent(sum)&&utils.isPent(dif)){
					utils.println("ANSWER:"+n+":"+j+":"+sum+":"+dif);
					solved = true;
					break;
				}
			}
			i++;
		}		
	}
}
